### ISSUE TITLE
能否出一个抢答的脚本

### ISSUE THREAD

**Issue by djkcyl** [Zy3122971650/course_ibodao#1]

**Comment by zy-nesime** [comment]
很抱歉过了这么长时间才注意到这个Issue，因为我需要使用ibodao的课程已经结束了，也因此这个仓库处于不活跃的状态。而且在我的课程里没有遇到需要抢答的内容，所以在我遇到需要抢答的内容之前，我可能不会去制作抢答的脚本。您也可以像我提供一些信息，我可能会去关注这个问题。
